### ISSUE TITLE
Any example on how to stream to an RTMP endpoint?

### ISSUE THREAD

**Issue by arisprung18** [Manevolent/ffmpeg4j#4]

**Comment by Manevolent** [comment]
I don't have any examples of this, but I have used ffmpeg4j successfully to (somewhat easily) stream to an RTMP endpoint.

The trick is to use `FFmpegIO.openNativeUrlOutput(String)`, where your first (and only) argument is in the format `rtmp://...`.  From there, you acquire an `FFmpegTargetStream` object, which you should pass the format `flv` to, and use the codecs `aac` for audio, and `libx254` for video.

Hope this helps!

**Comment by kinsleykajiva** [comment]
Hello sir do you care you have code worth sharing yet or sample to help us out on this part ?
