### ISSUE TITLE
Please update to current version of FFMpeg

### ISSUE THREAD

**Issue by eGit** [Manevolent/ffmpeg4j#9]
Also, is there a way to get a certain frame without decoding all the frames until that frame? For example if I want to get a VideoFrame 5min. into the video I have to use a loop and .next() many many times until that on frame that I want. This takes forever. I tried to achieve this with the API without any success. Methods like setPosition using Reflection but it has no effect when I subsequentially call next()

**Comment by Manevolent** [comment]
I have updated ffmpeg4j to ffmpeg 5.1.2 and I have added a seek feature to try and solve these big gaps
